# Generated by Django 2.2.8 on 2023-10-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
