# Generated by Django 4.1.12 on 2023-11-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0003_auto_20231006_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Transporte', 'Egreso por Transporte'), ('Alquiler', 'Alquiler'), ('Compras', 'Compras'), ('Trabajadores', 'Pago a Trabajadores'), ('Mantenimiento', 'Mantenimiento por Aventuras')], max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Restaurante', 'Restaurante'), ('Transporte', 'Transporte'), ('Hospedaje', 'Hospedaje de Cabañas'), ('Aventuras', 'Servicio de Aventuras')], max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
