"""

Generated by 'django-admin startproject' using Django 4.1.12.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import cloudinary
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-@6!c7@3j(b6_b1+bo=9_61(49ier5kialeighi$9a4mxp1^tb^'
SECRET_KEY = os.environ.get('SECRET_KEY', default='your secret key')


# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = 'RENDER' not in os.environ


ALLOWED_HOSTS = ["*"]

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'administrador',
    'usuarios',
    'reservaciones',
    'corsheaders',
    'channels'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'
# configuración de la funcuón asincronica
ASGI_APPLICATION = 'project.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}



# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

#mongodb+srv://christopheryahirm:<password>@cluster0.lnncvfj.mongodb.net/?retryWrites=true&w=majority

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'CLIENT': {
#             'host': config('HOST'),
#             'port': int(config('PORT')),
#         },
#         'NAME': 'sima_cotorras',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'sima_cotorras',
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host': 'mongodb+srv://223209:ek1oYJ5iDD48Is7C@clusterproyecto.a05vbix.mongodb.net/?retryWrites=true&w=majority/sima_cotorras',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

if not DEBUG:
    # Tell Django to copy statics to the `staticfiles` directory
    # in your application directory on Render.
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    # Turn on WhiteNoise storage backend that takes care of compressing static files
    # and creating unique names for each version so they can safely be cached forever.
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True  
# cors authorization
# CORS_ALLOWED_ORIGINS = [
#     "https://django-sima-cotorras2.onrender.com"
# ]

# congifuración de rutas para las imagenes locales
# MEDIA_ROOT = BASE_DIR / 'files'
# MEDIA_URL = '/media-files/'

# congifuración de rutas para las imagenes en cloudinary
cloudinary.config(
    cloud_name=config('CLOUD_NAME'),
    api_key=config('API_KEY'),
    api_secret=config('API_SECRET')
)

# === CLAVES EN MODO REAL === #
#STRIPE_PUBLIC_KEY = "pk_live_51O3jBUB4lOKww4uzgpS7EQArnmhZe6tGJHGnQPkTH35XK4IFQ9okZggJ0Us0B9mLCjIbiRcl29vCOI6AwpNPFrLm00jSKVLapW"
#STRIPE_SECRET_KEY = "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"

# === MODO DE PRUEBA === #
STRIPE_PUBLIC_KEY = "pk_test_51O3jBUB4lOKww4uzMOF61fXd7pHxq0FGsodZBo3ue7fR60XX1JFdUrjcMgS4M0IaQGbFYQXjPAd1xMSdcNbncvyF00xpLm1K2Y"
STRIPE_SECRET_KEY = "sk_test_51O3jBUB4lOKww4uzeFgFS8eZjHSxhIGUEk3M2k2AJ3f7jrwJT7ZRMjDB1FeKCwXILCXearLJE3kRFndfhbd57ZnG00AxJjIfQS"

STRIPE_WEBHOOK_SECRET = ""

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB