# Generated by Django 2.2.8 on 2023-10-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
                ('photo', models.ImageField(null=True, upload_to='files')),
            ],
        ),
    ]
