# Generated by Django 4.1.12 on 2023-11-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
