# Generated by Django 2.2.8 on 2023-10-07 18:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20231007_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Images'),
        ),
    ]
