# Generated by Django 4.1.12 on 2023-10-24 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Cabaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha', models.DateField(auto_now=True)),
                ('numero_transaccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaCabaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_reservacion', models.DateField()),
                ('fecha_de_salida', models.DateField()),
                ('cabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_de_cabaña', to='reservaciones.cabaña')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_de_cabaña', to='reservaciones.pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_de_cabaña', to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaAventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('aventura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_de_aventura', to='reservaciones.aventura')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_de_aventura', to='reservaciones.pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservacion_de_usuario', to='usuarios.usuarios')),
            ],
        ),
    ]
