# Generated by Django 4.1.12 on 2023-10-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabaña',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
