# Generated by Django 2.2.8 on 2023-10-11 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_comments'),
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCabaña',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_reservacion', models.IntegerField(max_length=200)),
                ('cabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_de_cabaña', to='reservaciones.Cabaña')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_de_cabaña', to='reservaciones.Pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_de_cabaña', to='usuarios.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaAventura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('aventura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_de_aventura', to='reservaciones.Aventura')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_de_aventura', to='reservaciones.Pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservacion_de_usuario', to='usuarios.Usuarios')),
            ],
        ),
    ]
