# Generated by Django 2.2.8 on 2023-10-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0002_reservaaventura_reservacabaña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='aventura',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_transaccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservacabaña',
            name='dias_reservacion',
            field=models.IntegerField(),
        ),
    ]
