# Generated by Django 4.1.12 on 2023-10-31 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0002_alter_cabaña_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabaña',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
