# Generated by Django 4.1.12 on 2023-11-10 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0003_cabaña_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aventura',
            name='price_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cabaña',
            name='price_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
